name: Client CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client_cicd.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build React App
        run: npm run build
        working-directory: ./client

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: ./client/build
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: ./client-build

      - name: Deploy to S3
        run: aws s3 sync ./client-build s3://$AWS_S3_BUCKET_NAME --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
